server:
  port: 8888
spring:
  application:
    name: servicecloud-oauth-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useSSL=false
    username: root
    password: root

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
security:
  basic:
    enabled: false  # 关闭http-basic方式的认证弹窗
  oauth2:
      resource:
        user-info-uri: http://localhost:9040/users/current
      client:
        client-id: admin
        client-secret: admin
        access-token-uri: http://localhost:9040/oauth/token
        grant-type: client_credentials,password
        scope: webclient
      authorization:
        check-token-access: http://localhost:9040/oauth/check_token
management:
  security:
    enabled: false
eureka:
   client:
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka/