server:
   port: 3344
   
spring:
   application:
      name: servicecloud-config
   cloud: 
      config: 
         server: 
            git: 
               uri: https://github.com/1711706065/servicecloud-config.git #GitHub上面的Git仓库