server:
  port: 9040
spring:
  application:
    name: servicecloud-oauth-server
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clouddb01?useSSL=false
      username: root
      password: root

      hikari:
        maximum-pool-size: 20
        minimum-idle: 5

  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: update
zuul:
  sensitive-headers: Cookie,Set-Cookie
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
eureka:
   client:
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka/